### ISSUE TITLE
How does refresh button work?

### ISSUE THREAD

**Issue by vicky002** [dhruvagarwal/geekometer#6]
When I'm clicking on Refresh Button... it should refresh the page right? I think it's not working.

**Comment by dhruvagarwal** [comment]
Oh wait ! you're not taking it correctly. It's not the refresh button as your browser. It functions as a decoration refresher on the page.For eg - you open many links from a page like DS or Algorithms and then you return to check progress, then instead of F5 you can use it .May not be of much use but i use it frequently.

**Comment by vicky002** [comment]
Ohh yeah ok I got your point! Thanks :)
